### ISSUE TITLE
compile error on ubuntu 17.10

### ISSUE THREAD

**Issue by i4kimura** [dvc94ch/riscv-rust-toolchain#4] opened 2017-12-02 02:07 UTC
Hi, 

I tried to build riscv-rust-toolchain on ubuntu 17.10 and I report I had some compile error.
At first compiler error was generated like "no such file or directory "llvm/Target/TargetSubtargetInfo.h" at src/rustllvm/PassWrapper.cpp.
So I modified like that:
```diff
diff --git a/src/rustllvm/PassWrapper.cpp b/src/rustllvm/PassWrapper.cpp
index fafa119498..7d5026cc52 100644
--- a/src/rustllvm/PassWrapper.cpp
+++ b/src/rustllvm/PassWrapper.cpp
@@ -22,7 +22,8 @@
 #include "llvm/Support/FileSystem.h"
 #include "llvm/Support/Host.h"
 #include "llvm/Target/TargetMachine.h"
-#include "llvm/Target/TargetSubtargetInfo.h"
+// #include "llvm/Target/TargetSubtargetInfo.h"
+#include "llvm/CodeGen/TargetSubtargetInfo.h"
 #include "llvm/Transforms/IPO/PassManagerBuilder.h"

 #if LLVM_VERSION_GE(4, 0)
```
Next, how can I use build-env.sh during build riscv-rust-toolchain?
During bulding, I got error like `error while loading shared libraries: "libLLVM-6.0svn.so"` and I needed to add `LD_LIBRARY_PATH` or `LIBRARY_PATH`. But build-env.sh can set them?

Could you check my modification is reasonable?

**Comment by dvc94ch** [comment] 2017-12-02 12:11
Yes the modification is reasonable, llvm moved these files recently. I probably didn't recompile rust since then.

I run `source build-env.sh` before running `make toolchain` which is written for a distro with a functional package manager like nixos or guix. But it's unnecessary for standard linux distros. I don't think you even need to set LIBRARY_PATH (it's for looking up *.a files not *.so files).

**Comment by dvc94ch** [comment] 2017-12-02 12:17
Can you check if this solves the problem?

```diff
diff --git a/Makefile b/Makefile
index 1846cac..c3043a0 100644
--- a/Makefile
+++ b/Makefile
@@ -59,6 +59,7 @@ $(sysroot_dir)/bin/cc:
 
 rust-build: $(sysroot_dir)/bin/cc
   # --disable-manage-submodules
+       LD_LIBRARY_PATH=$(sysroot_dir)/lib \
        cd $(rust_src) && \
        ./configure --enable-debug \
               --enable-extended \
```
Related-to: #2 

EDIT: This does not solve the problem

**Comment by i4kimura** [comment] 2017-12-03 06:39
Thank you for your support. After modifying Makefile as you show, I modified build-env.sh like that:
Because, there are no profile directory, 
- `export PATH` removes other `PATH` , so I modified to insert new path.
- `export GIT_EXEC_PATH` overwrite default git directory (after I set new GIT_EXEC_PATH, I can't use `git submodules`)
- I can't find profile/lib/libgcc_s.so.1, so I removed.

Could you check my modification is OK?

```diff
diff --git a/build-env.sh b/build-env.sh
index e84162c..1a43923 100755
--- a/build-env.sh
+++ b/build-env.sh
@@ -7,7 +7,7 @@ export SSL_CERT_DIR=/etc/ssl/certs
 export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
 export GUIX_LD_WRAPPER_ALLOW_IMPURITIES=y

-export PATH=$PROFILE/bin:$PROFILE/sbin
+export PATH=$PROFILE/bin:$PROFILE/sbin:${PATH}
 export C_INCLUDE_PATH=$PROFILE/include
 export CPLUS_INCLUDE_PATH=$PROFILE/include
 export LIBRARY_PATH=$PROFILE/lib
@@ -15,14 +15,14 @@ export LIBRARY_PATH=$PROFILE/lib
 export ACLOCAL_PATH=$PROFILE/share/aclocal
 export BASH_LOADABLES_PATH=$PROFILE/lib/bash
 export CMAKE_PREFIX_PATH=$PROFILE/
-export GIT_EXEC_PATH=$PROFILE/libexec/git-core
+# export GIT_EXEC_PATH=$PROFILE/libexec/git-core
 export TERMINFO_DIRS=$PROFILE/share/terminfo
 export PKG_CONFIG_PATH=$PROFILE/lib/pkgconfig
 export PYTHONPATH=$PROFILE/lib/python2.7/site-packages
 export INFOPATH=$PROFILE/share/info

 ##
-GCC_LIB=$(dirname $(dirname $(readlink profile/lib/libgcc_s.so.1)))
+# GCC_LIB=$(dirname $(dirname $(readlink profile/lib/libgcc_s.so.1)))
 export PATH=$TOOLCHAIN/bin:$PATH
 export LIBRARY_PATH=$TOOLCHAIN/lib:$GCC_LIB/lib:$LIBRARY_PATH
 ## (libgcc_s.so.1) needed to run bootstrap cargo and bootstrap rustc
```

And I confirmed `make toolchain` can complete successfully, and your `riscv-rust-quickstart` can build rust program.

**Comment by steynh** [comment] 2018-02-20 09:51
I'm also on Ubuntu 17.10 and got the `error while loading shared libraries: "libLLVM-6.0svn.so"` error at first. By adding `LD_LIBRARY_PATH=$(sysroot_dir)/lib \` to the makefile and making the modifications @msyksphinz mentioned, I managed to get past this error. I'm not sure if the changes in build-env.sh had any effect or that the Makefile change is enough, since I did both changes at the same time. The build-env.sh modifications seem reasonable though. 

Then I got an error with the note `note: /usr/bin/ld: cannot find -lLLVM-6.0svn`. I got around this by setting LIBRARY_PATH as well. 

After that everything built just fine and the `riscv-rust-quickstart` could build as well.

**Comment by sunnystormy** [comment] 2018-02-22 15:11
@steynh I have the same issue (using Debian Stretch). Trying both solutions hasn't worked for me yet, and I still end up with the "error while loading shared libraries..." prompt. :(

EDIT:

I think the issue is that the "rust-build" portion of the Makefile is unaware of where "libLLVM-6.0svn.so" is located. I know it's located within the "build/llvm/lib" directory, so it may be just a matter of making the build process aware of that? *shrug*

**Comment by steynh** [comment] 2018-03-01 13:29
@sunnystormy You can try setting those paths manually when you call `make toolchain`. Like `LIBRARY_PATH=... LD_LIBRARY_PATH=... make toolchain`.

**Comment by sunnystormy** [comment] 2018-03-01 13:41
@steyn Thank you for this! Will try it again and post my results! :D

**Comment by steynh** [comment] 2018-03-13 10:57
On the latest commit I still get an error about not finding libLLVM-6.0.so:

```
    Compiling rustc_llvm v0.0.0 (file:///home/steyn/riscv-rust-toolchain/rust/src/librustc_llvm)
error: failed to run custom build command for `rustc_llvm v0.0.0 (file:///home/steyn/riscv-rust-toolchain/rust/src/librustc_llvm)`
process didn't exit successfully: `/home/steyn/riscv-rust-toolchain/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/release/build/rustc_llvm-50548538c501b828/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=/home/steyn/riscv-rust-toolchain/rust/build/x86_64-unknown-linux-gnu/llvm/build/bin/llvm-config
cargo:rerun-if-env-changed=LLVM_CONFIG

--- stderr
/home/steyn/riscv-rust-toolchain/rust/build/x86_64-unknown-linux-gnu/llvm/build/bin/llvm-config: error while loading shared libraries: libLLVM-6.0.so: cannot open shared object file: No such file or directory
thread 'main' panicked at 'command did not execute successfully: "/home/steyn/riscv-rust-toolchain/rust/build/x86_64-unknown-linux-gnu/llvm/build/bin/llvm-config" "--version"
expected success, got: exit code: 127', build_helper/lib.rs:116:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Now, however, it cannot be fixed by setting LIBRARY_PATH and LD_LIBRARY_PATH.

**Comment by dvc94ch** [comment] 2018-03-13 11:10
That shouldn't be... The recommended way to get a working toolchain is to checkout riscv-rust, and build it, that should just work. Then build binutils, openocd separately or using riscv-rust-toolchain. Sorry that it's a PITA right now, hope to fix it soon...

**Comment by steynh** [comment] 2018-03-13 12:16
Ok, that's clear, so there's no need for riscv-rust-toolchain anymore unless you need binutils or openocd. 

Anyway, that's actually what I'm already doing now, although I cloned it through riscv-rust-toolchain and built llvm through the Makefile first (this is useless, but shouldn't hurt, right?).

I'll try to fix this error.

**Comment by steynh** [comment] 2018-03-14 09:08
I cleaned my build dir and tried it again. Worked like a charm this time.

**Closed as completed** 2018-07-26 13:57 UTC
